### ISSUE TITLE
Need to add "property_value" to the list in line 77

### ISSUE THREAD

**Issue by markwilkinson** [princelab/gene_ontology#1]
GO slims don't load at the moment.

https://github.com/princelab/gene_ontology/blob/ba8120e572b80871ed8603d719d96c83f7ba2ad3/lib/gene_ontology.rb#L77

There's a new GO property called "property_value".  If you add it to the list of properties in this line, the ontology will load  correctly (or at least, now it loads for me!)

Is it possible to update the Gem on rubygems?  I need it for my course, and don't want to ask my students to debug the code...

Cheers!

Mark

**Comment by jtprince** [comment]
fixed by #2
